backend:
  name: git-gateway
  repo: thomaswang/gatsby-personal-starter-blog

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: marketing
    label: Marketing-blog
    folder: content/marketing_blog
    create: true
    fields:
      - { name: header, label: header }
      - { name: date, label: Date }
      - { name: body, label: Body, widget: markdown }
